2025-01-19 11:32:22,380 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-19 11:34:03,374 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.DataError) (1265, "Data truncated for column 'id' at row 1")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '0e185a08-af4a-4f64-9311-8d732ad84320', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2025-01-19 11:36:00,292 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-19 11:36:08,650 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'mydatabase.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': 'bd4d9e9b-021d-40f3-a77c-6b7354d6e24f', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 11:36:14,299 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'mydatabase.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '3810b4c1-2eb3-4732-bf78-ed49fa2cbb72', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 11:36:49,567 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'mydatabase.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': 'da838aec-cb82-4ebf-a2fd-fb484bf44d73', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 11:38:23,782 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'mydatabase.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '047cbb5b-11e8-4606-a9e2-97107818c183', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 13:26:25,969 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '8f7a3fdb-b173-444a-9cb4-022d8be93354', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 13:26:29,777 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '58ddce1a-b8fd-4162-a49f-a4a7473ced7c', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 13:26:30,601 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': 'f8bcfe4c-bd12-43a9-9cc9-8bb7645b5f22', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 13:26:31,211 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '8c925046-429c-4d41-8752-dd2b75c0caf1', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-19 13:26:47,601 - ERROR - ❌ Database error in get_latest_posts(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '23368ffd-a00f-4bcc-8d2e-d4a024596901', 'visitor_ip': IPv4Address('182.214.56.194')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-21 12:02:55,799 - WARNING - email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
2025-01-21 12:03:13,089 - ERROR - ❌ Database error in save(): (pymysql.err.OperationalError) (1054, "Unknown column 'thumbnail_url' in 'field list'")
[SQL: INSERT INTO post (id, title, summary, content, created_at, likes_count, category, thumbnail_url) VALUES (%(id)s, %(title)s, %(summary)s, %(content)s, %(created_at)s, %(likes_count)s, %(category)s, %(thumbnail_url)s)]
[parameters: {'id': 'af4d0e88-76c6-4062-8061-be7d3edeaf3c', 'title': 'string', 'summary': 'string', 'content': 'string', 'created_at': '2025-01-21 12:02:38', 'likes_count': 0, 'category': <Category.DEVELOP: 'Develop'>, 'thumbnail_url': HttpUrl('https://example.com/')}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-21 12:04:08,303 - WARNING - email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
2025-01-21 12:04:14,131 - ERROR - ❌ Database error in save(): (pymysql.err.OperationalError) (1054, "Unknown column 'thumbnail_url' in 'field list'")
[SQL: INSERT INTO post (id, title, summary, content, created_at, likes_count, category, thumbnail_url) VALUES (%(id)s, %(title)s, %(summary)s, %(content)s, %(created_at)s, %(likes_count)s, %(category)s, %(thumbnail_url)s)]
[parameters: {'id': 'c55403e0-603c-445d-b49e-be3d85c1be54', 'title': 'string', 'summary': 'string', 'content': 'string', 'created_at': '2025-01-21 12:03:59', 'likes_count': 0, 'category': <Category.DEVELOP: 'Develop'>, 'thumbnail_url': HttpUrl('https://example.com/')}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-21 12:04:21,672 - ERROR - ❌ Database error in save(): (pymysql.err.OperationalError) (1054, "Unknown column 'thumbnail_url' in 'field list'")
[SQL: INSERT INTO post (id, title, summary, content, created_at, likes_count, category, thumbnail_url) VALUES (%(id)s, %(title)s, %(summary)s, %(content)s, %(created_at)s, %(likes_count)s, %(category)s, %(thumbnail_url)s)]
[parameters: {'id': '7ce16c94-be6b-4a6d-a059-c85ab1a22b18', 'title': 'string', 'summary': 'string', 'content': 'string', 'created_at': '2025-01-21 12:03:59', 'likes_count': 0, 'category': <Category.DEVELOP: 'Develop'>, 'thumbnail_url': HttpUrl('https://example.com/')}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-21 12:08:39,681 - WARNING - email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
2025-01-21 12:09:08,719 - ERROR - ❌ Database error in save(): (pymysql.err.OperationalError) (1054, "Unknown column 'thumbnail_url' in 'field list'")
[SQL: INSERT INTO post (id, title, summary, content, created_at, likes_count, category, thumbnail_url) VALUES (%(id)s, %(title)s, %(summary)s, %(content)s, %(created_at)s, %(likes_count)s, %(category)s, %(thumbnail_url)s)]
[parameters: {'id': 'a9e67af7-aa28-4304-b442-8e7c334091cf', 'title': 'string', 'summary': 'string', 'content': 'string', 'created_at': '2025-01-21 12:08:31', 'likes_count': 0, 'category': <Category.DEVELOP: 'Develop'>, 'thumbnail_url': HttpUrl('https://example.com/')}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-01-21 12:14:10,379 - WARNING - email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
2025-01-21 12:16:19,433 - ERROR - ❌ Database error in save(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '550e4609-9e7f-41f3-ae15-9f2e8a95a2c8', 'visitor_ip': IPv4Address('172.18.0.1')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-21 12:16:47,358 - ERROR - ❌ Database error in save(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '20e6a741-3e3f-4b2a-9018-2ba5c66603a4', 'visitor_ip': IPv4Address('172.18.0.1')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-21 12:21:49,955 - ERROR - ❌ Database error in save(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '1c633ca6-a9a2-40a7-8108-8ebfbe9b6d4e', 'visitor_ip': IPv4Address('172.18.0.1')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-21 12:22:31,148 - ERROR - ❌ Database error in save(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': 'e4d9cb84-357f-43ae-81d0-654c4b50af9a', 'visitor_ip': IPv4Address('172.18.0.1')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-21 12:24:20,638 - ERROR - ❌ Database error in save(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': '385fe028-776b-494e-9548-fb76be7d21a3', 'visitor_ip': IPv4Address('172.18.0.1')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-21 12:27:42,214 - ERROR - ❌ Database error in save(): (pymysql.err.ProgrammingError) (1146, "Table 'bang.visit_log' doesn't exist")
[SQL: INSERT INTO visit_log (id, visitor_ip) VALUES (%(id)s, %(visitor_ip)s)]
[parameters: {'id': 'b194c38a-b968-4c0f-aafa-c72e5ac52b52', 'visitor_ip': IPv4Address('172.18.0.1')}]
(Background on this error at: https://sqlalche.me/e/20/f405)
